remote_theme: pages-themes/modern@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
title: "MOTIONAURA: Generating High-Quality and Motion Consistent Videos Using Discrete Diffusion"
description: "A showcase of videos and their respective captions."
